# Generated by Django 2.2.5 on 2019-10-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzariaApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
