# Generated by Django 2.2.5 on 2019-10-01 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzariaApi', '0003_auto_20191001_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzariaApi.Cliente'),
        ),
    ]
